### ISSUE TITLE
namespacing serilizer class

### ISSUE THREAD

**Issue by fluxsaas** [stas/jsonapi.rb#1]
Hey!

awesome lib, just testing it out. what might be a good addition, is to set the namespace/path for serializer.

Use-Case: most likely you have a API with versions (v1, v2), and you might want to use different serializer_class for that.

https://github.com/stas/jsonapi.rb/blob/master/lib/jsonapi/rails.rb#L107

`
  render jsonapi: @users, serializer_class: "v1/users"
`

**Comment by stas** [comment]
Thanks, @fluxsaas! It was on my list so I finally managed to dedicate some time for it.

I took a bit of a different route and updated the renderer to look if there's a controller method responsible for resolving the resource serializer. Unfortunately, we are using the serializer class to render the errors too (to provide the `pointer` source) so having it inline doesn't help much.

I updated the readme with examples as well. Let me know if this solution didn't help.
:bowing_man:

**Comment by fluxsaas** [comment]
sweet. refactored and all test are green!

for anybody else looking, here is a an example:

````ruby
class V1::UsersController < V1Controller
  include JSONAPI::Pagination
  include JSONAPI::Filtering

  # GET /users
  def index
    allowed = [:email]
    jsonapi_filter(User.all, allowed) do |filtered|
      jsonapi_paginate(filtered.result) do |paginated|
        render jsonapi: paginated
      end
    end
  end

  # GET /users/1
  def show
    render jsonapi: User.find(params[:id])
  end

end
````

````ruby
class V1Controller < ApplicationController

  private

  def jsonapi_serializer_class(resource, is_collection)
    klass = resource.class
    klass = resource.first.class if is_collection
    return "V1::#{klass.name}Serializer".constantize
  end

end
````
