### ISSUE TITLE
Issues using custom scopes

### ISSUE THREAD

**Issue by drj17** [stas/jsonapi.rb#14]
Hey, thanks for the great work on this gem.

I'm trying to figure out how to get custom scopes to work, but it seems like this method in filtering.rb is stripping them out https://github.com/stas/jsonapi.rb/blob/a4a16e54b7f5a2569486f70777e741da9a2f6772/lib/jsonapi/filtering.rb#L59-L67

Is there a reason that filter options without predicates are removed?  I have a scope called `awaiting_review_by_user_id`.  I've added it to the ransackable scopes, and that works fine, but the method above removes it anyways.  Is there an easy way to get this scope working? Locally removing the `predicates.any?` check fixed my issue, but maybe I'm missing something that's already built in.

**Comment by stas** [comment]
@drj17 would you be kind to provide some code, I'm not sure I understand what exactly fails. We are using this for filtering on scopes internally without any issues.

Just after a quick look, consider renaming the scope to something that includes also a predicate, instead of `awaiting_review_by_user_id` use `awaiting_review_user_id_eq`.

Generally speaking, you can extend the list of predicates and add anything to it (including a dummy predicate), but there should be something, otherwise things will get messy.

**Comment by drj17** [comment]
Hi @stas 

I've put together a small sample project here https://github.com/drj17/jsonapi_sample

I can send a request to ` http://localhost:8081/todos?filter[awaiting_review_by_user_id]=some_user_id` and when I put a debugger  in `jsonapi_filter_params` I can see predicates is empty, causing filtered to return `{}`

I did try changing the name to `awaiting_review_by_user_id_eq`, and I was able to get it working only if the allowed fields did not include the predicate (`allowed = [:awaiting_review_by_user_id]`) but the scope and request did.  Maybe this is intended?

**Comment by stas** [comment]
> I did try changing the name to `awaiting_review_by_user_id_eq`, and I was able to get it working only if the allowed fields did not include the predicate (`allowed = [:awaiting_review_by_user_id]`) but the scope and request did. Maybe this is intended?

Yes, unfortunately this is how Ransack is also designed...
I reviewed the example you put together and I can confirm that having the scope follow the naming to include the predicate is the right way to do it... 

Glad it worked for you.

Long-term, it would be nice to find a lighter alternative to ransack... but at the moment, I prefer to rely on what we have...

Thanks @drj17! Feel free to close the issue if that's ok with you.

**Comment by drj17** [comment]
Good to know.  It might be worthwhile to have an example or caveat in the readme for cases like this, but it's nice have gotten it working without too much tweaking.

**Comment by stas** [comment]
Unfortunately working with filters requires quite a bit of knowledge of Ransack. If you have some time to document the use-case, I'll be happy to merge it!

Thanks again :upside_down_face:
