### ISSUE TITLE
Mongoid Issue

### ISSUE THREAD

**Issue by CaleCrawford** [stas/jsonapi.rb#2]
Hello,

Love this idea and this project. Thank you for working on it. While installing I ran into a problem and I can't seem to figure it out. 
- I installed the jsonapi.rb gem 
- Then installed the ransack-mongoid lib `gem 'ransack-mongoid', github: 'activerecord-hackery/ransack-mongoid'`

Then when I start the rails server i get the error: 
`lib/jsonapi/patches.rb:37:in 'alias_method': undefined method 'visit_Ransack_Nodes_Sort' for class 'Ransack::Visitor' (NameError)`

Which look like its here: https://github.com/stas/jsonapi.rb/blob/master/lib/jsonapi/patches.rb#L37.

Because I'm using mongoid i have active_record turned off. Could that be part of the problem?
Newish to rails and unfamiliar with ransack so any direction or ideas would be appreciated. 
Thanks!

**Comment by joel** [comment]
I @CaleCrawford `jsonapi.rb` relied on https://github.com/activerecord-hackery/ransack who support ActiveRecord by default, I don't think `jsonapi.rb` was tested for Mongoid. However, Ransack can support it, see https://github.com/activerecord-hackery/ransack#mongoid and https://github.com/activerecord-hackery/ransack-mongoid. Maybe the owner will add the support of Mongoid later.

**Comment by CaleCrawford** [comment]
@joel Thanks for the reply! Yeah unfortunately that error is using the ransack-mongoid lib. The issue is
https://github.com/stas/jsonapi.rb/blob/master/lib/jsonapi/patches.rb#L37 with overriding the method `visit_Ransack_Nodes_Sort`. For some reason that is causing issues without active_record or with mongoid

**Comment by stas** [comment]
@CaleCrawford, thanks for reporting this. As @joel mentioned, Mongoid support was not really in the scope of this little tool.

I prepared a branch where the `patches.rb` are loaded only if the active record is present. I will appreciate if you could give it a try. If it doesn't work, we will have to set up a more solid testing environment using Mongoid:
https://github.com/stas/jsonapi.rb/tree/ransack_sans_active_record

Thanks in advance!

**Comment by CaleCrawford** [comment]
@stas Thank you very much for creating the branch. Unfortunately it seems to break other pieces. I am using namespaced serializers and the method `jsonapi_serializer_class` is not running. I believe that the issue is the `visit_Ransack_Nodes_Sort` method not being implemented here: https://github.com/activerecord-hackery/ransack-mongoid/blob/master/lib/ransack/adapters/mongoid/ransack/visitor.rb like it is here: https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/adapters/active_record/ransack/visitor.rb. I dont know enough about ransack to implement `visit_Ransack_Nodes_Sort` in the mongoid version. Thank you for the lib. Maybe ill try and learn a bit more about how it works and implement a mongoid version

**Comment by stas** [comment]
No worries @CaleCrawford, thank for bringing this up. I'll be happy to review if you find/have patches to get it working.

As for the serializers, please follow the documentation on how it works:
https://github.com/stas/jsonapi.rb#object-serialization

This is being used already in some projects and I could not see any issues with it.
