### ISSUE TITLE
There is no way to return page with more than 30 items

### ISSUE THREAD

**Issue by rafaltrojanowski** [stas/jsonapi.rb#24]
Recently we've found that with `page[size]` parameter greater than `30` is omitted in the response.

```
    "meta": {
        "pagination": {
            "current": 1
        },
        "page_size": 30,
        "total_count": 100
    }
```
It works well with lower numbers, so I was wondering - is it a protection for performance reasons or rather unexpected thing? :)

## Expected Behavior

Page size equals 50 and returns 50 items

## Actual Behavior

Page size equals 30 and returns 30 items

## Steps to Reproduce the Problem

  1. Add pagination
  2. Add query param ?page[size]=50
  3. Check response and meta page_size, which is 30 in this case.

## Specifications

  - Version: 1.5.7
  - Ruby version: 2.7.1p83

**Comment by stas** [comment]
Heya,
actually it's just a safe default. Just set the constant `JSONAPI_PAGE_SIZE = 50` in your controller and it will be picked up automatically.

Example:
```ruby
class MyController < ActionController::Base
  include JSONAPI::Pagination

  JSONAPI_PAGE_SIZE = 50

  def index
    jsonapi_paginate(Model.all) do |paginated|
      render jsonapi: paginated
    end
  end
end
```

Let me know if this works for you :)
