### ISSUE TITLE
Recomended javascript library

### ISSUE THREAD

**Issue by aguirrel-sesocio** [stas/jsonapi.rb#26]
Hi!

Do you have some recomendation for a frontend library in javascript?

Thanks a lot!

Best regards,

**Comment by stas** [comment]
Hi there @aguirrel-sesocio,
on a regular basis I've been using Ember.js which includes the API adapter for JSON:API, I can't say too much regarding React though. I think my friend @sungraze did work with Vue.js and JSON:API (hopefully he can share his feedback).

If anybody in the React world has suggestions, feel free to share them folks!

**Comment by jfanals** [comment]
We are using Vue.js with this gem and it works great

**Comment by aguirrel-sesocio** [comment]
Hi @jfanals 
Thanks for your response! 

Are you using some js package to manage jsonapi standard or you are parsing jsonapi at your own?

**Comment by sienic** [comment]
@aguirrel-sesocio I'd recommend you https://github.com/danivek/json-api-serializer, it handles both serialisation and deserialisation, while remaining simple and convenient.

**Comment by stas** [comment]
@aguirrel-sesocio please consider the official website for suggestions:
https://jsonapi.org/implementations/#client-libraries-javascript

:bow:
