### ISSUE TITLE
Documentaion error in Deserialization?

### ISSUE THREAD

**Issue by dgavey** [stas/jsonapi.rb#3]
Hi there, just starting to implement this library.  

I was trying out the deserialization and it was returning blank (in a rails 6 controller). Your readme shows the deserialization method called like this

`jsonapi_deserialize(only: [:attr1, :rel_one])`

But that didn't work, looking into your code, it looked like I need to pass the params directly.

`jsonapi_deserialize(params, only: [:attr1, :rel_one])`

Not sure if it's just a documentation error, or maybe something else.  Just wanted to check in about it.

**Comment by stas** [comment]
@dgavey you're right, it's a documentation mistake. Reviewing the tests, confirms this:
https://github.com/stas/jsonapi.rb/blob/master/spec/deserialization_spec.rb#L53-L59

I'll try to update the docs in the next days, if you're faster, I'll be happy to merge the changes.

Thanks for reporting this! :bow:

**Comment by dgavey** [comment]
Oh great,  thanks for the quick confirmation! Really like the small, easy to read nature of this library.  Hopefully I can contribute a bit if I come across any issues.

**Comment by stas** [comment]
Wonderful! Happy to help!
