### ISSUE TITLE
new jsonapi_page_size option

### ISSUE THREAD

**Issue by fluxsaas** [stas/jsonapi.rb#37]
Hello!

regarding the new `jsonapi_page_size` implementation, i would like to suggest to always call the method `jsonapi_page_size` even if the params `page[size]` is passed to the request:

https://github.com/stas/jsonapi.rb/blob/3a685a766e12fd5be9176af7e2a54c5c2a7f7a62/lib/jsonapi/pagination.rb#L97-L104

a use case could be to implement a logic to set/overwrite the max size of a response:

```ruby
def jsonapi_page_size
  pagination = params[:page].try(:size) || {}
  per_page = pagination[:size] || 50
  per_page = 50 if per_page.to_f.to_i > 50
  return per_page
end
```

best ✌️

**Comment by stas** [comment]
Hey @fluxsaas!
Would you be kind to send a PR please :smiley: :bow:

**Comment by fluxsaas** [comment]
@stas 

sure, do you want to raise an exception if `per_page < 1 ` or just let the user handle the situation?

best

**Comment by stas** [comment]
There should be no exceptions. Thank you!
