### ISSUE TITLE
Off-by-one error when paginating an array

### ISSUE THREAD

**Issue by petronius** [stas/jsonapi.rb#4]
https://github.com/stas/jsonapi.rb/blob/2a7c645925ed9876bdd90f4f880e19f19053db46/lib/jsonapi/pagination.rb#L19

When paginating based on an array, the line above should read:
```
resources = resources[(offset)..(offset + limit - 1)]
```
otherwise there will always be an extra element in each page.

To give a trivial example, if you were using this to paginate with a page size of 1, starting on page 2:
```
> resources = [0,1,2,3,4,5,6,7,8,9,10]
=> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
> offset = 1
=> 1
> limit = 1
=> 1
> resources[(offset)..(offset + limit)]
=> [1, 2]
```
however:
```
> resources[(offset)..(offset + limit - 1)]
=> [1]
```

**Comment by stas** [comment]
@petronius thank you for the report!

I reviewed your example and it looks like we already have a test for it, could you confirm please this is the test-case you're describing:
https://github.com/stas/jsonapi.rb/blob/master/spec/pagination_spec.rb#L57-L98

I'll take some time a bit later to play with the numbers you've sent, but I'll definitely appreciate if you could use our tests to exemplify the issue.

**Comment by stas** [comment]
Closing this since there's no feedback.

**Comment by jf** [comment]
@stas can we reopen the issue? It's still a problem. There are 2 key things here:
1. when `jsonapi_paginate` gets passed an array (so `!resources.respond_to?(:offset)`), the pagination returns one more resource than it should (off by one)
2. it seems that `jsonapi_paginate` does its work to apply pagination before `jsonapi_pagination_meta` gets called. When `resources` is an array, the info about the actual size of the resources is lost when `jsonapi_pagination_meta` calls `.size` on it

**Comment by stas** [comment]
@jf I'll add a test with an array. Thanks for the feedback.

**Comment by stas** [comment]
v1.5.4 is out, @petronius @jf thanks for helping with this!
