### ISSUE TITLE
Potentially simple improvement to increase flexibility

### ISSUE THREAD

**Issue by sspread** [stas/jsonapi.rb#46]
This line https://github.com/stas/jsonapi.rb/blob/4f7d4b76e32bd91ff3e919fb5c8d141df9b51b7f/lib/jsonapi/rails.rb#L102 triggers a query to check for an empty collection: `any?` == `exists?` (i.e. `select 1`), which removes scopes containing `select` attached to the chain, and throwing db error when creating using virtual field names in the select later referenced in the same query (i.e. `where` filter).

Proposed non-breaking simple solution: instead of `any?`, use `limit(1).present?` so rails doesn't do its magic conversion to a `select 1` query.

**Comment by stas** [comment]
@sspread thank you! Would you be kind to share a test-case please. I believe we're using the `any?` just to make sure it works with a non-rails dataset (arrays and any enumerable in fact).

**Comment by sspread** [comment]
@stas I'll add some detail to my use case and I'd like to hear your thoughts.

Before passing my collection to the jsonapi_filter, I'm querying my collection with a scope that adds attributes (i.e. sum/count via SQL column alias `AS`). In model I'm adding ransacker mapping to the virtual attributes (i.e. `ransacker(:virtual_column) {Arel.sql('virtual_attribute')})` so that I can sort/filter by them per query params using the existing ransack predicates. 

However, because of the condition in my original post, the sql `where` condition remains (which may contain my virtual attributes), while the generation of these virtual attributes (which happens in my `select`) gets stripped, resulting in invalid sql statement. 

So for my case to work, the `any?` code that causes rails to (rather implicitly) replace my scoped `select` statement with a `select` clause of its own must be changed to something that does not cause rails to do that (i.e. my proposal in OP).

**Comment by stas** [comment]
@sspread I agree, the best would be for us to have a look at a real use-case, so please go ahead and share it and I'll be happy to review it!

Btw, please take a look at this note before:
https://github.com/stas/jsonapi.rb/blob/master/README.md#sorting-using-expressions

**Comment by sspread** [comment]
@stas I looked at your link in docs. That loosely addresses the issue, but the core of it is using virtual attribute. The case I outlined IS basically the real use case. Here's that simplified scenario for clarity:

relevant parsed filter query params: `{virtual_attribute_gteq: 100}`

invalid sql generated by `any?` code before yielding to block provided by `jsonapi_filter` : `SELECT 1 AS one FROM my_table WHERE my_table.virtual_attribute >= 100.0) GROUP BY my_table.id`

I can provide `my_table.virtual_attribute` in a scope on the collection passed to `jsonapi_filter`. This works for SORTING by the virtual column, but when FILTERING by it (as in example), the sql is invalid because of `any?` replacing my scope `select` I need with `SELECT 1 AS one`.

**Comment by stas** [comment]
@sspread sorry, by real use-case I was trying to suggest to provide an code-based example I could reproduce :see_no_evil: 

It could help me look into the issue, otherwise, I'll need a bit more time.

**Comment by sspread** [comment]
Here's a PR to illustrate a simple test case for the outcome I seek. This differs from my actual case in that I'm using postgres and my own pagination module. If you run only the test in my PR it will fail on the count query (for pagination). If you ignore pagination (i.e. comment out pagination in controller), it will fail in filter (I think sqlite (but not postgres) wants `having` instead of `where` when grouping). If you resolve that, I suppose you'll arrive at the original issue I posted about.

So, with this PR I attempted to create an example in the context of your existing test environment, but it lead me to new issues. 

From a feature perspective, I want to serialize the notes quantity sum per user record, and allow filtering based on that value.

**Comment by sspread** [comment]
@stas Looking into this more, I realize that to query by aggregate, valid sql would have to be `having` vs `where`, and I'm not sure how ransack handles that. I'm having trouble finding documentation on it and I'm confused about this line in jsonapi.rb docs:

> You can use basic aggregations like min, max, avg, sum and count when sorting. This is an optional feature since SQL aggregations require grouping. To enable expressions along with filters, use the option flags:

Does this purport to handle filter by aggregate?

Anyway, this whole use case is probably more complicated than I originally thought. I'd appreciate any thoughts you may have, but this has become more of an open discussion than a specific "issue" per se.

**Comment by sspread** [comment]
@stas I figured out how to do what I wanted - putting those aggregate query columns in a join table rather than the select statement. This bypasses the original issue I raised. Closing this. Thanks for listening :)
