### ISSUE TITLE
filter using scope doesn't work

### ISSUE THREAD

**Issue by khrisnagunanasurya-iav** [stas/jsonapi.rb#50]
## Expected Behavior
`?filter[status]=active` should only return active bookings only

and the `Ransack::Search` 
should return `Ransack::Search<class: Booking, scope: {"status"=>"active"}, base: Grouping <combinator: and>>`
(need to return the same ransack search object when using Ransack directly using this code`
```
Booking.ransack(status: "active")
```

## Actual Behavior
Return all bookings and the ransack search object return this `Ransack::Search<class: Booking, base: Grouping <combinator: and>>`
without `scope: {"status"=>"active"}`, so the endpoints return all bookings without scope

## TheController
```
  def index
    allowed_fields = %i[
      status
      created_at
      updated_at
    ]

    bookings = Booking.where(user: current_user)
    jsonapi_filter(bookings, allowed_fields) do |filtered|
      jsonapi_paginate(filtered.result) do |paginated|
        render jsonapi: paginated
      end
    end
  end
```

**Comment by stas** [comment]
Hi there @khrisnagunanasurya-iav 

> `?filter[status]=active` should only return active bookings only

This doesn't look like a valid filter param. Precisely, there's a predicate missing. Consider using `?filter[status_eq]=active`

For more context, please take a look at:
https://github.com/stas/jsonapi.rb#filtering-and-sorting
and
https://github.com/activerecord-hackery/ransack#search-matchers

I'll be closing this, but please do feel free to leave updates if you still have questions :bow:
