### ISSUE TITLE
Using without ActiveRecord

### ISSUE THREAD

**Issue by artofhuman** [stas/jsonapi.rb#55]
jsonapi.rb depends on  `ransack` which crashed if application used without ActiveRecord. (https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/adapters.rb#L14) for example, if we use Sequel.

Do we have a workaround to use this lib without active record?

**Comment by stas** [comment]
@artofhuman totally agree, no need to make Ransack a hard dep.

In fact we can refactor the `require` calls to leave a warning if Ransack is not available, the rest should work just fine, like we did here:
https://github.com/stas/jsonapi.rb/blob/master/lib/jsonapi/deserialization.rb#L1-L9

The only relevant file is just this one:
https://github.com/stas/jsonapi.rb/blob/master/lib/jsonapi/filtering.rb#L1-L2

**Comment by stas** [comment]
@artofhuman, the ransack is no longer a hard dependency. Please let me know if this is still an issue. Relevant PR #76 :bow:
