### ISSUE TITLE
Error on `jsonapi_pagination_meta` when using a grouped collection

### ISSUE THREAD

**Issue by khrisnagunanasurya-iav** [stas/jsonapi.rb#60]
## Expected Behavior
Grouped resources pagination should pass

## Actual Behavior
Got error
```
undefined method `to_f' for {2=>5, 3=>6, 1=>2}:Hash
Did you mean?  to_s
               to_a
               to_h
```

## Steps to Reproduce the Problem

  1. include JSONAPI::Pagination
  2. implement jsonapi_meta
  ```
    def jsonapi_meta(resources)
    pagination = jsonapi_pagination_meta(resources)

    { pagination: pagination } if pagination.present?
  end
  ```
  3. Add collection which grouped `Model.left_joins(:another_models).group(:some_model_attribute).select("models.*, COUNT(another_models.id) AS custom_attribute")`

## Specifications
  - JSONAPI Version: 1.7.0
  - Rails Version: 6.1.3
  - Ruby version: 3.0.0

## Suggestion
I think it's better to use `.length` instead `.size`, so it will work with grouped resources

https://github.com/stas/jsonapi.rb/blob/a28f6d4a9f8545a8dcf4536f48f838a015df499c/lib/jsonapi/pagination.rb#L68

same with here

https://github.com/stas/jsonapi.rb/blob/a28f6d4a9f8545a8dcf4536f48f838a015df499c/lib/jsonapi/pagination.rb#L72

**Comment by stas** [comment]
I left a detailed explanation on the #61
