### ISSUE TITLE
When using OJ, colons prepended to keys in the response 

### ISSUE THREAD

**Issue by Ji-You** [stas/jsonapi.rb#65]
Hello, first of all thank you very much for your dedication in maintaining this project.
I'm trying to hook up OJ, by following the example shown in `jsonapi-serializer` repository, but for some reason the response looks weird. Could you please point me in the right direction?
## Expected Behavior
```
{
  "data": {
    "id": "999",
    "type": "user"
  }
}
```
## Actual Behavior
```
{
  ":data": {
    ":id": "999",
    ":type": "user"
  }
}
```

## Steps to Reproduce the Problem

  1. Extend from `BaseSerializer` (https://github.com/jsonapi-serializer/jsonapi-serializer/blob/master/docs/json_serialization.md)
  2. Invoke `render jsonapi: model`

## Specifications

  - Version: 1.7.0
  - Ruby version: 2.5.8

**Comment by Ji-You** [comment]
Please disregard this issue. I digged into `oj` documentation, and found a solution. What I had to do was add `mode: :compat` (`Oj.dump(hash, mode: :compat`)

For reference:
https://github.com/ohler55/oj/issues/54

**Comment by stas** [comment]
Consider adding an initializer with:`
```ruby
# config/initializers/oj.rb
require 'oj'

Oj.optimize_rails()

# Disable encoding of HTML entities in JSON.
ActiveSupport.escape_html_entities_in_json = false
```

**Comment by stas** [comment]
@Ji-You I'll close this for now, please feel free to reopen if it's still an issue. Thank you!
