### ISSUE TITLE
Includes don't seem to get paginated?

### ISSUE THREAD

**Issue by johnmcdowall** [stas/jsonapi.rb#67]
If you set up pagination on your primary resource, it gets paginated fine. Now imagine that someone includes a relationship in the query, and that result set is in the 1000s. 

What I see happening right now is that the top level resource is paginated correctly, but any included fields are fetched in total with no pagination whatsoever. 

Is this expected? How can it be made so that anything included is also paginated correctly?

**Comment by stas** [comment]
Hi @johnmcdowall 

Apologies for the late reply.

I don't think the spec is covering this aspect, ultimately the includes should be limited to the relevant records withing the current _page_.

Feel free to reopen this if you find something is off :bow:
