### ISSUE TITLE
Using dot notation for relationship attributes when sorting

### ISSUE THREAD

**Issue by xhs345** [stas/jsonapi.rb#71]
## Expected Behavior
Based on the JsonAPI spec it is recommended to use the dot notation for relationships:

> Note: It is recommended that dot-separated (U+002E FULL-STOP, “.”) sort fields be used to request sorting based upon relationship attributes. For example, a sort field of author.name could be used to request that the primary data be sorted based upon the name attribute of the author relationship.

(https://jsonapi.org/format/#fetching-sorting)

## Actual Behavior
Based on the Ransack implementation an underscore is used to combine relationship model name and the attribute (e.g. `author_name`).

I'm not aware of any workarounds for this, so was curious is anyone else ran into this or just ignored the recommendation.

**Comment by stas** [comment]
Hey @xhs345 

As you put it very well, it's a recommendation. Afaik JSONAPI does not enforce the syntax on filters or sorting attributes.

To me, feel free to ignore it :)

**Comment by xhs345** [comment]
One interesting case I ran into today:

User model with field `groups_count` and model also has association `groups`. count is being considered a predicate, so the query wouldn't work. I ended up adding option `sort_with_expressions: true` and allow sort attribute `groups` and luckily it still ended up working this way (it used `groups_count` in the SQL query)
