### ISSUE TITLE
JSONAPI::Rails.is_collection? confused by 'size' attribute

### ISSUE THREAD

**Issue by dmolesUC** [stas/jsonapi.rb#75]
## Expected Behavior

- Single model instance with `size` attribute is recognized as not a collection

## Actual Behavior

- Single model instance with `size` attribute mistakenly believed to be a collection
  due to [this heuristic](https://github.com/stas/jsonapi.rb/blob/v1.7.0/lib/jsonapi/rails.rb#L132) in `JSONAPI::Rails.is_collection?`
- Serialization fails with `NoMethodError` when attempting to call `any?` [here](https://github.com/stas/jsonapi.rb/blob/v1.7.0/lib/jsonapi/rails.rb#L102) in `JSONAPI::Rails.add_renderer!`

## Steps to Reproduce the Problem

  1. Create a model with an attribute `size` of type `string`.
  2. Try to serialize it, e.g. with `render jsonapi: @the_instance` in a controller method.

## Possible solutions

Consider using `resource.is_a?(Enumerable)` instead of `respond_to?(:any?)`. This seems to be what [jsonapi-serializer does now](https://github.com/jsonapi-serializer/jsonapi-serializer/blob/v2.2.0/lib/fast_jsonapi/object_serializer.rb#L115) after first realizing `size` was a problem and [trying `each` instead](https://github.com/jsonapi-serializer/jsonapi-serializer/commit/0edebd99e663832bf4d279376d54b18bc34e0c4f), then deciding that was [more trouble than it was worth](https://github.com/jsonapi-serializer/jsonapi-serializer/issues/112).

## Specifications

  - Version: 1.7.0
  - Ruby version: 3.0.3
  - jsonapi-serializer version: 2.2.0

**Comment by stas** [comment]
Hey,
thanks for the issue @dmolesUC 

You're right, this needs to be updated, as we already did in https://github.com/jsonapi-serializer/jsonapi-serializer/pull/75
(probably as easy as to just call the `jsonapi-serializer` implementation :thinking: )

Happy to merge it if you have time to prepare a PR.

**Comment by dmolesUC** [comment]
@stas Will do. I had a look at calling the `json-serializer` implementation, but since it's inside a `class_methods` block it was nontrivial, so I'm just going to do it the easy way for now.
