### ISSUE TITLE
Filtering on relational table properties

### ISSUE THREAD

**Issue by ekampp** [stas/jsonapi.rb#8]
First off. This is by far the best JSON:API tool I have found. I salute you! 

Secondly, I have a user table, which has email and name, I also have an access table, which stores access logs. 

The user serializer has the latest login time as a first-class property, but on a db level it's not a first-class property. 

What's the recommended way that I go about Using `JSONAPI:Filtering` (and in turn Ransack) to filter on related properties? 

Based on this section of the [Ransack Readme](https://github.com/activerecord-hackery/ransack#ransacks-search_form_for-helper-replaces-form_for-for-creating-the-view-search-form), it looks like I could use `filter[access_created_at_match]`. 

But I would like to separate the presentation layer (where it's a first-class property) from the database layer (where it's an association). I would like this separation to extend to the parameters the client can send to my resource endpoints.

Thanks in advance.

**Comment by stas** [comment]
> First off. This is by far the best JSON:API tool I have found. I salute you!

Thank you! :relaxed:

Answering your question... Assuming the `access` in the `access_created_at` is a relationship (I believe a `belongs_to`/`has_one`), indeed you could rename the serializer attribute, or consider using a [ransacker](https://github.com/activerecord-hackery/ransack/wiki/Using-Ransackers) to define the _shortcut_. I also used successfully Ransack with scopes through `ransackable_scopes`.

I try to keep just a list of filterables in the controller and keep the logic somewhere else.

I'm sorry if this is a vague answer, generally there's no _opinionated_ implementation, so it's mostly up to you how to make Ransack happy and what to use in the serializers. The filterable module needs just a list of attributes it allows filtering upon in the end.

I hope this helps, but please let me know if I misunderstood something, I'll be happy to help :bowing_man:

**Comment by ekampp** [comment]
I was not aware of Ransackers. I will give them a good, long look, and I will get back to you and let you know if that solved the problem or not.

**Comment by ekampp** [comment]
Hey, @stas, I found this, which completely fixes my filtering. Thanks for the links and the help! 

```ruby
ransack_alias :created_at, :access_created_at
```

But this breaks sorting via `JSONAPI::Pagination`, because `created_at` isn't a first-class property on the resource. 

Any suggestions here?

**Comment by stas** [comment]
> I realize (and agree) that this should be left our because it's application-specific, but I think the lib could benefit from examples on how to handle these cases, where resources are not exactly matching the data structure underneath.

@ekampp I agree, though we should mainly try to help here the Ransack project. Unfortunately their documentation is indeed not the most straight forward. I also had to do quite a bit of hacking to get some basic relationship aliases to work.

My long-term goal though is to keep things slightly coupled. Mainly because there are alternative projects[1] similar to Ransack and as much as I like the project, there are some design decisions that complicate a lot the solutions to such simple issues like yours.

If I'd have to make a decision, I'd probably keep things as Ransack sees them, and not try to put too much effort if this is just an aesthetics concern. Alternatively, `ransacker` might be the only way this can be achieved :|

[1]: https://github.com/mrkamel/search_cop

**Comment by ekampp** [comment]
Sorting isn't done in ransack, though, right?

**Comment by stas** [comment]
> Sorting isn't done in ransack, though, right?

It is haha:
https://github.com/stas/jsonapi.rb/blob/master/lib/jsonapi/filtering.rb#L73-L101

**Comment by ekampp** [comment]
Ah.. I see. In that case, yes, the problem is either with Ransack's code or documentation. Thanks for helping me understand how sorting and filtering was implemented. And I agree to keep the coupling loose.
