### ISSUE TITLE
warning to install ransack polute logs

### ISSUE THREAD

**Issue by gagalago** [stas/jsonapi.rb#84]
## Expected Behavior
no log about ransack if we don't use filtering and don't have ransack installed

## Actual Behavior
we have a [warning](https://github.com/stas/jsonapi.rb/blob/master/lib/jsonapi/filtering.rb#L6) when this file is [loaded](https://github.com/stas/jsonapi.rb/blob/master/lib/jsonapi.rb#L3) by jsonapi.rb gem

## Steps to Reproduce the Problem

  1. start the app without ransack gem installed
  2. look at logs

## Proposition of solution

One way to fix this is to not load this file on the gem and let the user loading it when they need it (as already explained in the readme). That will need to bump the major version of the gem but should not affect people that already followed the readme.

What do you think? do you see another way to fix it? it's not a bug but a feature and you prefer to keep it as is?

**Comment by stas** [comment]
Ah, thanks for the report!

This is related to #64 change, and I honestly would like to keep it like that, at least until a larger release is out.
The idea is that folks upgrading to this ransack-less version, should be warned about the change in deps.

Is it ok if we keep it like this until the next major release?

**Comment by gagalago** [comment]
we can live with it. it create confusion every 2-3 months in my team when someone new look at logs so not an hard blocker for me.

Another option that I see is to move the require in the [`extract_attributes_and_predicates`](https://github.com/stas/jsonapi.rb/blob/master/lib/jsonapi/filtering.rb#L16) to lazy require it and add a log as a [post-install message](https://guides.rubygems.org/specification-reference/#post_install_message) to keep warning people.

what do you think about this second proposition?

**Comment by stas** [comment]
@gagalago that works too. Happy to merge it if you have some time to submit the change :pray:

**Comment by stas** [comment]
Fixed in 1f60bdf
