### ISSUE TITLE
allow any field for allow fields?

### ISSUE THREAD

**Issue by curtis741** [stas/jsonapi.rb#88]
I'm used to using ransack but this is the first time I've been using it through jsonapi.rb. I'm a bit annoyed that I have to set what fields I can allow filtering on. I guess I could do this:
```
jsonapi_filter(User.all, User.column_names, options) do |filtered|
  render jsonapi: result.group('id').to_a
end
```

But then if I set up a ransack scope to filter with I'd have to combine it with this. I guess I just want allowed_fields to be an optional field (maybe default nil?) and then if it's nil, don't restrict what can be filtered on.

Are there any qualms about this? I could setup a PR to allow for that, doesn't look like it'd be too involved.

**Comment by stas** [comment]
@curtis741 the way Ransack works could open attack vectors if we don't filter out the attributes. Eg. ransack could build joined queries for filters, which could hit relationships with attributes which are not indexed. I'd not advise for not using at least some sort of list of allowed filters, so I'll definitely have concerns merging anything like that :see_no_evil: 

If you really want to _disable_ it, you could overwrite the relevant `JSONAPI::Filtering::jsonapi_filter()` and feed anything directly to the good old `ransack()` method:
https://github.com/stas/jsonapi.rb/blob/master/lib/jsonapi/filtering.rb#L39-L45

Hope this helps :wink:

**Comment by curtis741** [comment]
@stas thanks for the reply. I understand that as a general approach and agree that it makes sense.

In my situation It's not a public API and we've got a strong authorization layer with very granular permissions. A bad actor like that would be a known party and we'd be able to address it with them easily enough. The strong authorization layer makes this less of a concern. 

We are more worried about the way things can be included so we've been leveraging `jsonapi_include` a lot.

Thanks for the prompt response and the tip, I'll close this issue as answered.
