### ISSUE TITLE
How to deserialize a collection?

### ISSUE THREAD

**Issue by thomascchen** [stas/jsonapi.rb#94]
Am I correct that the `jsonapi_deserialize` method is meant to only deserialize a document containing a single resource object? Is there a recommended approach for deserializing a document containing an array of resource objects, as with a GET request that returns a collection?

**Comment by stas** [comment]
@thomascchen please review the issues/conversation in the underlying gem related to this functionality, eg:
https://github.com/jsonapi-serializer/jsonapi-serializer/issues/121#issuecomment-1244697268

Gonna close this as the project doesn't directly provide this functionality.
